### ISSUE TITLE
type validation of polymorphic opcode is not consistent with the wasm specification

### ISSUE THREAD

**Issue by laizy** [go-interpreter/wagon#143]
file  test.wast:
```wast
(module
  (type $t0 (func (param i32) (result i32)))
  (func $add_one (export "add_one") (type $t0) (param $p0 i32) (result i32)
	unreachable
	i64.const 0
	i32.const 1
	i32.add
  ))
```
convert  to wasm format with wat2wasm (disable check):
```bash
wat2wasm --no-check test.wast -o test.wasm
```
use wasm-validate: 
```bash
$ wasm-validate test.wasm
test.wasm:000002c: error: type mismatch in i32.add, expected [i32, i32] but got [i64, i32]
```
use `VerifyModule` in wagon it passed.

**Comment by laizy** [comment]
the wasm spec has a sound and complete algorithm defined in  https://webassembly.github.io/spec/core/appendix/algorithm.html

**Comment by carltraveler** [comment]
I think this is ok with wasm spec.  https://webassembly.github.io/spec/core/valid/instructions.html#polymorphism   

> The unreachable instruction is valid with type [t∗1]→[t∗2] for any possible sequences of value types t∗1 and t∗2

. Consequently,
unreachable  i32.add

is valid by assuming type []→[i32 i32]
for the unreachable

instruction. In contrast,
unreachable  (i64.const 0)  i32.add

is invalid, because there is no possible type to pick for the unreachable
instruction that would make the sequence well-typed.

>

**Comment by twitchyliquid64** [comment]
This seems to be caused by most types checks looking like this:

```go
if !vm.isPolymorphic() && (under || op.Type != t) {
	return InvalidTypeError{t, op.Type}
}
```

Instead of disabling stack/type checking if the current frame is polymorphic, we should invent a new type, the `Unknown` type, and push that to the stack. Then, any type check with the unknown type should succeed.

Likewise disabling the stack underflow check looks bad.

**Comment by twitchyliquid64** [comment]
Okay, investigating this more, we have to assume unknown contents of the stack at the return from the stack polymorphic instructions, hence we need to disable the stack underflow check. However, we should not disable the type checking - if there is a value on the stack, then we should validate it.
